#################################################################################################
#
# Automation
#


#################################################################################################
# Lights
- alias: Turn on lights at sunset
  trigger:
    platform: sun
    event: sunset
    offset: '00:30:00'
  action:
    service: switch.turn_on
    entity_id:
      - switch.garden_lights
      - switch.hall_lights

- alias: Turn off lights at bedtime
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: switch.turn_off
    entity_id:
      - switch.garden_lights
      - switch.hall_lights
    
