#################################################################################################
#
# Automation
#


#################################################################################################
# Lights
- alias: Turn on lights at sunset
  trigger:
    platform: sun
    event: sunset
    offset: '00:30:00'
  action:
    service: switch.turn_on
    entity_id:
      - switch.garden_lights
      - switch.hall_lights

- alias: Turn off lights at bedtime
  trigger:
    platform: template
    value_template: "{{ states.sensor.time.state == (states.input_datetime.bedtime.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  action:
    service: switch.turn_off
    entity_id:
      - switch.garden_lights
      - switch.hall_lights
    
