#################################################################################################
#
# Sensors
#


#################################################################################################
# Weather Underground
- platform: wunderground
  api_key: d8bb7894bfaa8297
  pws_id: IEDINBUR91 
  monitored_conditions:
    - alerts
    - wind_gust_mph
    - temp_c
    - feelslike_c

- platform: time_date
  display_options: 
    - 'time'
