#################################################################################################
# 
# Switches
#


#################################################################################################
# 433MHz Sockets
- platform: rpi_rf
  gpio: 17
  switches:
    Hall Lights:
      code_on: 16408079
      code_off: 16408078
      signal_repetitions: 20

    switch_2:
      code_on: 16408077
      code_off: 16408076
      signal_repetitions: 20


#################################################################################################
# TP-Link Sockets
- platform: tplink
  host: 192.168.0.19
  name: Garden Lights
